### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jntdst** [google/grain#333]
File "C:\Users\moriyantez\PycharmProjects\tf210\lib\site-packages\grain\_src\python\lazy_dataset\transformations\shuffle.py", line 18, in <module>
    from grain._src.python.experimental.index_shuffle.python import index_shuffle_module as index_shuffle
ImportError: cannot import name 'index_shuffle_module' from 'grain._src.python.experimental.index_shuffle.python' (unknown location)

**Comment by aireenmei** [comment]
How did you install grain?
Grain does not support installing from github. Please use pip install grain-nightly

**Comment by nireekshak** [comment]
Hi @jntdst ,
I have tested in a Colab environment, installed both Grain and the grain-nightly version, and I was able to import `index_shuffle_module` successfully. Attaching a [gist](https://colab.sandbox.google.com/gist/nireekshak/6cf43bb634962959cf3c9b9befa2bc58/-333.ipynb) for your reference.Could you please verify on your end and let me know if the issue still persists.Thanks!

**Comment by jeelania10** [comment]
Hi @jntdst,


As @nireekshak verified, the index_shuffle_module now imports successfully with the current Grain package. I also verified the import and shuffle functionality with `Grain 0.2.18` in the attached Colab [gist](https://colab.sandbox.google.com/gist/jeelania10/7cc09bf5a9cf6393346e653229043922/grain-333.ipynb). Grain also added a Windows build in `v0.2.12`. 


Please refer to the official [Grain documentation](https://google-grain.readthedocs.io/en/stable/changelog.html?#grain-0-2-12-august-21-2025) for reference.
Closing this issue based on the above verification. Please feel free to reopen it if the problem is not fully resolved.
